name: Update Japan IP List with Manual Routes for Nginx

on:
  schedule:
    - cron: '0 17 * * *'  # 每天 UTC 时间 17:00（北京时间 01:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install aggregate (for IPv4 CIDR aggregation)
        run: |
          sudo apt update
          sudo apt install -y aggregate

      - name: Fetch Japan IP list
        run: |
          # 下载日本 IP 地址列表
          curl -s http://www.iwik.org/ipcountry/JP.cidr -o jp_cidr_raw.txt
          
          # 去除 # 号开头的注释行，并去重
          grep -v '^#' jp_cidr_raw.txt | sort -u > jp_cidr.txt

          # 使用 aggregate 进行 IPv4 CIDR 聚合
          aggregate < jp_cidr.txt > jp_cidr_aggregated.txt

          # 直接合并手动维护的 manual_routes.txt（确保它不会被 aggregate 过滤）
          if [[ -f manual_routes.txt ]]; then
            cat manual_routes.txt >> jp_cidr_aggregated.txt
          fi

          # 去重 & 生成最终的 Nginx 配置文件（修复格式问题）
          sort -u jp_cidr_aggregated.txt | awk '{print $0 " yes;"}' > nginx_jp_ip_list.conf
          
          # 检查第一行是否只有"yes;"，如果是，则删除它
          if grep -q "^yes;" nginx_jp_ip_list.conf; then
            sed -i '1d' nginx_jp_ip_list.conf
          fi

          # 显示最终结果（可选）
          echo "===== Final Nginx IP List ====="
          cat nginx_jp_ip_list.conf

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # 添加文件到暂存区
          git add nginx_jp_ip_list.conf
          
          # 提交更改，使用 --allow-empty 强制提交，即使没有文件变更
          git commit -m "Update Japan IP list [$(date -u)]" --allow-empty
          
          # 推送到远程仓库
          git push
