name: Update Japan IP List with Manual Routes for Nginx

on:
  schedule:
    - cron: '0 17 * * *'  # 每天 UTC 时间 17:00（北京时间 01:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install aggregate (for IPv4 CIDR aggregation)
        run: |
          sudo apt update
          sudo apt install -y aggregate

      - name: Fetch Japan IP list
        run: |
          # 下载日本 IP 地址列表
          curl -s http://www.iwik.org/ipcountry/JP.cidr -o jp_cidr_raw.txt
          
          # 去除 # 号开头的注释行，并去重
          grep -v '^#' jp_cidr_raw.txt | sort -u > jp_cidr.txt

          # 使用 aggregate 进行 IPv4 CIDR 聚合
          aggregate < jp_cidr.txt > jp_cidr_aggregated.txt

          # 直接合并手动维护的 manual_routes.txt（确保它不会被 aggregate 过滤）
          if [[ -f manual_routes.txt ]]; then
            cat manual_routes.txt >> jp_cidr_aggregated.txt
          fi

          # 确保输出是干净的 CIDR 列表
          grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$' jp_cidr_aggregated.txt > cleaned_jp_cidr.txt || true

          # 去重 & 生成最终的 Nginx 配置文件
          sort -u cleaned_jp_cidr.txt | awk '{print $0 " yes;"}' > nginx_jp_ip_list.conf || true
          
          # 检查结果
          echo "===== Final Nginx IP List (first 10 lines) ====="
          head nginx_jp_ip_list.conf || true

      - name: Auto commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Japan IP list"
          file_pattern: "nginx_jp_ip_list.conf"
          commit_options: "--no-verify"
          push_options: "--force"
          skip_dirty_check: true  # 即使没有变化也提交
