name: Update Japan IP List with Manual Routes for Nginx

on:
  schedule:
    - cron: '0 17 * * *'  # 每天 UTC 时间 17:00（北京时间 01:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史

      - name: Install aggregate (for IPv4 CIDR aggregation)
        run: |
          sudo apt update
          sudo apt install -y aggregate

      - name: Fetch Japan IP list
        run: |
          # 下载日本 IP 地址列表
          curl -s http://www.iwik.org/ipcountry/JP.cidr -o jp_cidr_raw.txt
          
          # 去除 # 号开头的注释行，并去重
          grep -v '^#' jp_cidr_raw.txt | sort -u > jp_cidr.txt

          # 使用 aggregate 进行 IPv4 CIDR 聚合
          aggregate < jp_cidr.txt > jp_cidr_aggregated.txt

          # 直接合并手动维护的 manual_routes.txt（确保它不会被 aggregate 过滤）
          if [[ -f manual_routes.txt ]]; then
            cat manual_routes.txt >> jp_cidr_aggregated.txt
          fi

          # 确保输出是干净的 CIDR 列表(只包含有效IP)
          grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$' jp_cidr_aggregated.txt > cleaned_jp_cidr.txt

          # 去重 & 生成最终的 Nginx 配置文件
          sort -u cleaned_jp_cidr.txt | awk '{print $0 " yes;"}' > nginx_jp_ip_list.conf
          
          # 检查结果
          echo "===== Final Nginx IP List (first 10 lines) ====="
          head nginx_jp_ip_list.conf

      - name: Force commit and push with pull
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # 先拉取远程更改
          git pull origin main --rebase
          
          # 强制添加文件
          git add -f nginx_jp_ip_list.conf
          
          # 提交更改
          git commit -m "Update Japan IP list [$(date -u)]" --allow-empty
          
          # 推送更改
          git push origin main
