name: Update Japan IP List with Manual Routes for Nginx

on:
  schedule:
    - cron: '0 17 * * *'  # 每天 UTC 时间 17:00（北京时间 01:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install aggregate (for IPv4 CIDR aggregation)
        run: |
          sudo apt update
          sudo apt install -y aggregate

      - name: Fetch Japan IP list
        run: |
          # 下载日本 IP 地址列表
          curl -s http://www.iwik.org/ipcountry/JP.cidr -o jp_cidr_raw.txt
          
          # 去除 # 号开头的注释行，并去重
          grep -v '^#' jp_cidr_raw.txt | sort -u > jp_cidr.txt

          # 使用 aggregate 进行 IPv4 CIDR 聚合
          aggregate < jp_cidr.txt > jp_cidr_aggregated.txt

          # 直接合并手动维护的 manual_routes.txt（确保它不会被 aggregate 过滤）
          if [[ -f manual_routes.txt ]]; then
            cat manual_routes.txt >> jp_cidr_aggregated.txt
          fi

          # 确保目录存在
          mkdir -p all_ips_nginx

          # 去重 & 生成最终的 Nginx 配置文件
          sort -u jp_cidr_aggregated.txt | awk '{print $0 " yes;"}' > all_ips_nginx/nginx_jp_ip_list.conf
          
          # 检查第一行是否只有"yes;"，如果是，则删除它
          if grep -q "^yes;" all_ips_nginx/nginx_jp_ip_list.conf; then
            sed -i '1d' all_ips_nginx/nginx_jp_ip_list.conf
          fi

      - name: Force commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # 强制添加文件，无论是否存在或有变化
          git add -f all_ips_nginx/nginx_jp_ip_list.conf
          
          # 提交更改
          git commit -m "Update Japan IP list [$(date -u)]" --allow-empty
          
          # 强制推送更改
          git push
