name: Update Japan IP List with Manual Routes for Nginx

on:
  schedule:
    - cron: '0 17 * * *'  # 每天 UTC 时间 17:00（北京时间 01:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install aggregate (for IPv4 CIDR aggregation)
        run: |
          sudo apt update
          sudo apt install -y aggregate
          rm -f nginx_jp_ip_list.conf  # 确保旧文件被删除

      - name: Fetch Japan IP list
        run: |
          # 下载 IP 列表
          curl -s http://www.iwik.org/ipcountry/JP.cidr -o jp_cidr_raw.txt
          
          # 去除注释行
          grep -v '^#' jp_cidr_raw.txt | sort -u > jp_cidr.txt

          # 进行 CIDR 聚合
          aggregate < jp_cidr.txt > jp_cidr_aggregated.txt

          # 合并手动维护的 manual_routes.txt
          if [[ -f manual_routes.txt ]]; then
            cat manual_routes.txt >> jp_cidr_aggregated.txt
          fi

          # 生成 Nginx 配置文件
          sort -u jp_cidr_aggregated.txt | awk '{print $0 " yes;"}' > nginx_jp_ip_list.conf

          # 添加时间戳，确保文件总是变化
          echo "Last updated: $(date -u)" >> nginx_jp_ip_list.conf

          # 确保文件正确生成
          ls -l nginx_jp_ip_list.conf
          cat nginx_jp_ip_list.conf

      - name: Commit and push changes (force commit)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # 添加所有更改
          git add .

          # 强制提交，即使没有内容变化
          git commit -m "Force update Japan IP list on $(date -u)" --allow-empty
          
          # 强制推送
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
